<?php

/**
 * @file
 * Contains activite.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function activite_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the activite module.
    case 'help.page.activite':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('activite') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function activite_theme() {
  $theme = [];
  $theme['activite'] = [
    'render element' => 'elements',
    'file' => 'activite.page.inc',
    'template' => 'activite',
  ];
  $theme['activite_content_add_list'] = [
    'render element' => 'content',
    'variables' => ['content' => NULL],
    'file' => 'activite.page.inc',
  ];
  return $theme;
}

/**
* Implements hook_theme_suggestions_HOOK().
*/
function activite_theme_suggestions_activite(array $variables) {
  $suggestions = [];
  $entity = $variables['elements']['#activite'];
  $sanitized_view_mode = strtr($variables['elements']['#view_mode'], '.', '_');

  $suggestions[] = 'activite__' . $sanitized_view_mode;
  $suggestions[] = 'activite__' . $entity->bundle();
  $suggestions[] = 'activite__' . $entity->bundle() . '__' . $sanitized_view_mode;
  $suggestions[] = 'activite__' . $entity->id();
  $suggestions[] = 'activite__' . $entity->id() . '__' . $sanitized_view_mode;
  return $suggestions;
}
