<?php

/**
 * @file
 * Contains projet.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function projet_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the projet module.
    case 'help.page.projet':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Gestion des projets') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function projet_theme() {
  $theme = [];
  $theme['projet'] = [
    'render element' => 'elements',
    'file' => 'projet.page.inc',
    'template' => 'projet',
  ];
  $theme['projet_content_add_list'] = [
    'render element' => 'content',
    'variables' => ['content' => NULL],
    'file' => 'projet.page.inc',
  ];
  return $theme;
}

/**
* Implements hook_theme_suggestions_HOOK().
*/
function projet_theme_suggestions_projet(array $variables) {
  $suggestions = [];
  $entity = $variables['elements']['#projet'];
  $sanitized_view_mode = strtr($variables['elements']['#view_mode'], '.', '_');

  $suggestions[] = 'projet__' . $sanitized_view_mode;
  $suggestions[] = 'projet__' . $entity->bundle();
  $suggestions[] = 'projet__' . $entity->bundle() . '__' . $sanitized_view_mode;
  $suggestions[] = 'projet__' . $entity->id();
  $suggestions[] = 'projet__' . $entity->id() . '__' . $sanitized_view_mode;
  return $suggestions;
}
