<?php

/**
 * @file
 * Contains motifavenant.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function motifavenant_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the motifavenant module.
    case 'help.page.motifavenant':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Les motifs de l&#039;avenant') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function motifavenant_theme() {
  $theme = [];
  $theme['motifavenant'] = [
    'render element' => 'elements',
    'file' => 'motifavenant.page.inc',
    'template' => 'motifavenant',
  ];
  $theme['motifavenant_content_add_list'] = [
    'render element' => 'content',
    'variables' => ['content' => NULL],
    'file' => 'motifavenant.page.inc',
  ];
  return $theme;
}

/**
* Implements hook_theme_suggestions_HOOK().
*/
function motifavenant_theme_suggestions_motifavenant(array $variables) {
  $suggestions = [];
  $entity = $variables['elements']['#motifavenant'];
  $sanitized_view_mode = strtr($variables['elements']['#view_mode'], '.', '_');

  $suggestions[] = 'motifavenant__' . $sanitized_view_mode;
  $suggestions[] = 'motifavenant__' . $entity->bundle();
  $suggestions[] = 'motifavenant__' . $entity->bundle() . '__' . $sanitized_view_mode;
  $suggestions[] = 'motifavenant__' . $entity->id();
  $suggestions[] = 'motifavenant__' . $entity->id() . '__' . $sanitized_view_mode;
  return $suggestions;
}
