<?php

/**
 * @file
 * Contains travaux.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function travaux_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the travaux module.
    case 'help.page.travaux':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Liste des travaux') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function travaux_theme() {
  $theme = [];
  $theme['travaux'] = [
    'render element' => 'elements',
    'file' => 'travaux.page.inc',
    'template' => 'travaux',
  ];
  $theme['travaux_content_add_list'] = [
    'render element' => 'content',
    'variables' => ['content' => NULL],
    'file' => 'travaux.page.inc',
  ];
  return $theme;
}

/**
* Implements hook_theme_suggestions_HOOK().
*/
function travaux_theme_suggestions_travaux(array $variables) {
  $suggestions = [];
  $entity = $variables['elements']['#travaux'];
  $sanitized_view_mode = strtr($variables['elements']['#view_mode'], '.', '_');

  $suggestions[] = 'travaux__' . $sanitized_view_mode;
  $suggestions[] = 'travaux__' . $entity->bundle();
  $suggestions[] = 'travaux__' . $entity->bundle() . '__' . $sanitized_view_mode;
  $suggestions[] = 'travaux__' . $entity->id();
  $suggestions[] = 'travaux__' . $entity->id() . '__' . $sanitized_view_mode;
  return $suggestions;
}
