<?php

/**
 * @file
 * Contains obsfonciermodule.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Form\FormStateInterface;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Drupal\Core\Url;

/**
 * Implements hook_help().
 */
function obsfonciermodule_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the obsfonciermodule module.
    case 'help.page.obsfonciermodule':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Module pour Observatoire du Foncier') . '</p>';
      return $output;

    default:
  }
}

/**
 * un user doit arrive sur la liste des projets quand il se connecte, sauf la première fois
 * hook_user_login($account) */
function obsfonciermodule_user_login($account){

	if (in_array('ministere', \Drupal::currentUser()->getRoles())) {
        $url_object = \Drupal::service('path.validator')->getUrlIfValid('/liste-des-projets');
	    $url_object->setAbsolute();
	    $url = $url_object->toString();
	    $response = new RedirectResponse($url);
	    $response->send();
	}
}

function getOptions($table) {

	$options = array();
    $nids = \Drupal::entityQuery($table)
    		->execute();
    $datas = \Drupal::entityTypeManager()->getStorage($table)->loadMultiple($nids);
    foreach ($datas as $nid => $data) {
    	$options[$nid] = $data->get('name')->getValue()['0']['value'];
    }
    asort($options);
    return $options;
}  

function obsfonciermodule_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {

	
	
	if (in_array($form_id, array('entreprise_type1_edit_form', 'entreprise_type1_add_form'))) {
		//Supprime le bouton de suppression dans les form
		unset($form['actions']['delete']);
		
		//On appelle la fonction qui fera la redirection
		$form['actions']['submit']['#submit'][] = 'obsfonciermodule_liste_entreprise';
		}
	
	if (in_array($form_id, array('permisminier_type1_add_form', 'permisminier_type1_edit_form', 
		'permisautorisation_type1_add_form', 'permisautorisation_type1_edit_form',
		'contrat_type1_add_form', 'contrat_type1_edit_form'))) {
		
		//Supprime le bouton de suppression dans les form
		unset($form['actions']['delete']);
		
		//On appelle la fonction qui fera la redirection
		$form['actions']['submit']['#submit'][] = 'obsfonciermodule_edit_entreprise';
		  
		}
}  

function obsfonciermodule_liste_entreprise(array &$form, FormStateInterface $form_state) {
	//On redirige vers la liste des entreprises
	$type = "projet_maj";
	send_mail($type);
	$form_state->setRedirect('obsfonciermodule.liste_entreprise');
}


function obsfonciermodule_edit_entreprise(array &$form, FormStateInterface $form_state) {
	//On redirige vers l'entreprise/projet en édition
	$values = $form_state->getValues();
	$option = array('entreprise' => $values['entreprise_id']);
	$type = "contrat_maj";
	send_mail($type);
	$form_state->setRedirect('obsfonciermodule.edit_entreprise', $option);
}

function send_mail($type) {
	//A chaque update ou create, on va envoyer un email au responsable de l'obs du foncier
	
	
	 $mailManager = \Drupal::service('plugin.manager.mail');
	 $module = 'obsfonciermodule';
	 switch($type) {
	 	case 'contrat_add':
        	$msg = "Le contrat a été créé";
        	break;
    	case 'contrat_maj':
        	$msg = "Le contrat a été mis à jour";
        	break;
       	case 'permisminier_add':
        	$msg = "Le permis minier a été créé";
        	break;
    	case 'permisminier_maj':
        	$msg = "Le permis minier a été mis à jour";
        	break;
        case 'permisautorisation_add':
        	$msg = "L'autorisation a été créé";
        	break;
    	case 'permisautorisation_maj':
        	$msg = "L'autorisation a été mise à jour";
        	break;
        case 'projet_add':
        	$msg = "Le projet a été créé";
        	break;
    	case 'projet_maj':
        	$msg = "Le projet a été mis à jour";
        	break;
       }
	 
	 $key = $type; // Replace with Your key
	 $to = "ingenosya.guillaume@gmail.com";
	 $from = 'OBSERVATOIRE DU FONCIER';
	 $subject = "OBSERVATOIRE DU FONCIER - Projet ...";
	 $langcode = \Drupal::currentUser()->getPreferredLangcode();
	 $send = true;
	
	 //$result = $mailManager->mail($module, $key, $to, $langcode, $params, NULL, $send);
	 
	 //Utilisateur connecté
	 $idUser = \Drupal::currentUser()->id();
	 $user = \Drupal\user\Entity\User::load($idUser);
	 //kint($user->getUsername());
	 $userConnected = $user->getDisplayName();
	 $emailConnected = $user->getEmail();
	 $msgUser = "Utilisateur responsable de la modification : ".$userConnected." (".$emailConnected.")";
	 
	  	
	 $message = [
        'id' => 'drupal_mail_obsfoncier' ,
        'headers' => ['Content-type' => 'text/html; charset=UTF-8; format=flowed; delsp=yes'],
        'subject' => $subject,
        'from' => $from,
        'to' => $to,
        'body' => "Bonjour<br><br>".$msg."<br><br>,
      ];
      $mailManager->getInstance(['module' => $module, 'key' => $key])->mail($message);
	 
	 
	 if ($result['result'] != true) {
	    $message = t("Il y a eu un problème en envoyant l'email à @email.", array('@email' => $to));
	    drupal_set_message($message, 'error');
	    \Drupal::logger('mail-log')->error($message);
	    return;
	 }
	
	 $message = t('Un email a été envoyé à @email ', array('@email' => $to));
	 drupal_set_message($message);
	
}
	
	