<?php

/**
 * @file
 * Contains obsfonciermodule.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Form\FormStateInterface;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Drupal\Core\Url;

/**
 * Implements hook_help().
 */
function obsfonciermodule_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the obsfonciermodule module.
    case 'help.page.obsfonciermodule':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Module pour Observatoire du Foncier') . '</p>';
      return $output;

    default:
  }
}

/**
 * un user doit arrive sur la liste des projets quand il se connecte, sauf la première fois
 * hook_user_login($account) */
function obsfonciermodule_user_login($account){

	if (in_array('ministere', \Drupal::currentUser()->getRoles())) {
        $url_object = \Drupal::service('path.validator')->getUrlIfValid('/liste-des-projets');
	    $url_object->setAbsolute();
	    $url = $url_object->toString();
	    $response = new RedirectResponse($url);
	    $response->send();
	}
}

function getOptions($table) {

	$options = array();
    $nids = \Drupal::entityQuery($table)
    		->execute();
    $datas = \Drupal::entityTypeManager()->getStorage($table)->loadMultiple($nids);
    foreach ($datas as $nid => $data) {
    	$options[$nid] = $data->get('name')->getValue()['0']['value'];
    }
    asort($options);
    return $options;
}  

function obsfonciermodule_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {

	
	
	if (in_array($form_id, array('entreprise_type1_edit_form', 'entreprise_type1_add_form'))) {
		//Supprime le bouton de suppression dans les form
		unset($form['actions']['delete']);
		
		//On appelle la fonction qui fera la redirection
		$form['actions']['submit']['#submit'][] = 'obsfonciermodule_liste_entreprise';
		}
	
	if (in_array($form_id, array('permisminier_type1_add_form', 'permisminier_type1_edit_form', 
		'permisautorisation_type1_add_form', 'permisautorisation_type1_edit_form',
		'contrat_type1_add_form', 'contrat_type1_edit_form'))) {
		
		//Supprime le bouton de suppression dans les form
		unset($form['actions']['delete']);
		
		//On appelle la fonction qui fera la redirection
		$form['actions']['submit']['#submit'][] = 'obsfonciermodule_edit_entreprise';
		  
		}
}  

function obsfonciermodule_liste_entreprise(array &$form, FormStateInterface $form_state) {
	//On redirige vers la liste des entreprises
	$form_state->setRedirect('obsfonciermodule.liste_entreprise');
}


function obsfonciermodule_edit_entreprise(array &$form, FormStateInterface $form_state) {
	//On redirige vers l'entreprise/projet en édition
	$values = $form_state->getValues();
	$option = array('entreprise' => $values['entreprise_id']);
	$form_state->setRedirect('obsfonciermodule.edit_entreprise', $option);
}